### PR TITLE
Adjust Stream#files to return attachments to be consistent with Upload#files

### LINKED ISSUE #875: Un-normalized files listed in resourcelist resolve to the wrong files.
URLs listed in a streams resourcelist for harvesting un-normalized data resolve to the wrong files:

https://pod.stanford.edu/organizations/mit/streams/pod_stream/resourcelist
https://pod.stanford.edu/file/40702/POD_ALMA_EXPORT_20220421_220411%5B019%5D_new_9.xml

The file above should be a MARC XML file with 100,000 records submitted by MIT, instead it downloads a delete file submitted by duke.

### PR DESCRIPTION
**Pull request by corylown**
Closes #875

### CODE REVIEW

**Comment by cbeer** [comment]
Aren't we already constructing urls using the attachment id?

https://github.com/pod4lib/aggregator/blob/ebb3fd9c4c09ef3c0ed8af8103c48bcb13ff86f8/config/routes.rb#L82

**Comment by corylown** [comment]
@stream.files are blobs though, right?: https://github.com/pod4lib/aggregator/blob/ebb3fd9c4c09ef3c0ed8af8103c48bcb13ff86f8/app/views/streams/show.xml.builder#L13

**Comment by cbeer** [comment]
Ha. `Stream#files` are blobs, `Upload#files` are attachments.

**Comment by cbeer** [comment]
Makes sense to me. `Stream#files` seems like it'll be easier to track down all the references?

**Pull request merged**
