### PR TITLE
Fix duplication in display of users and organizations 

### PR DESCRIPTION
**Pull request by marlo-longley**

### CODE REVIEW

**Comment by corylown** [comment]
@marlo-longley I think Chris's comment was leading in the correct direction for a fix. You can add the following to the Organization model:

`  has_many :users, -> { distinct }, through: :roles, class_name: 'User', source: :users`

Then you can get each distinct user through an organization:

`Organization.where(slug: 'stanford').first.users`

And each of their roles:

`Organization.where(slug: 'stanford').first.users.first.roles`

Then the views can be updated to use this method of fetching users and roles to avoid display duplication.

**Comment by marlo-longley** [comment]
@corylown thanks for looking Cory. I wanted to change the underlying logic so that users could not have both the owner and member role at once. Your solution just changes the view. Is this acceptable?

**Comment by corylown** [comment]
I'm not convinced that a user having more than one role is problematic other than the display issue. This fixes the model so we can display users how people expect.

**Comment by marlo-longley** [comment]
@corylown ok thanks for clarifying! I think I was reading the ticket title too literally. Will update soon.

**Comment by marlo-longley** [comment]
Fixes #638 
Not sure if there was an issue for the navbar duplication too.

**Review by corylown — APPROVED** [review]

**Pull request merged**
